apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: < docker-image > #vishant07/kafka-manager:v1
        ports:
        - containerPort: 80
        env:
        - name: ZK_HOSTS
          value: zk-svc.test:2181
        command:
        - ./bin/kafka-manager
        - -Dhttp.port=80
