kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: test
spec:
  selector:
    app: kafka-manager
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30028
  externalIPs:
    - < externalIP >
